### ISSUE TITLE
[FEATURE] UnRAID template

### ISSUE THREAD

**Issue by Jacob-Lasky** [jamcalli/Pulsarr#41]
I'd love for there to be an UnRAID template in the UnRAID community app "store." It'd make it a lot more accessible to me (and other UnRAID users)!

Here's a walkthrough of what would be needed: https://forums.unraid.net/topic/57181-docker-faq/#comment-566084 .

If you're not familiar with UnRAID, it's a Linux based OS which runs docker containers and is managed via a web UI.

**Comment by wigglesdetroit** [comment]
Me too!

**Comment by marksmaynard1** [comment]
Me three

**Comment by jamcalli** [comment]
@Jacob-Lasky 
@wigglesdetroit 
@marksmaynard1 

I don't mind doing this, but I dont use UnRAID.

Can someone generate the xml for me? 

I can do the rest.

**Comment by Jacob-Lasky** [comment]
Sure thing! I'll get to it this weekend :)

**Comment by jamcalli** [comment]
I am still waiting on the xml.

Here is a compose without the .env. The TZ variable is required for the next release. 

```
services:
  pulsarr:
    image: lakker/pulsarr:latest
    container_name: pulsarr
    ports:
      - "3003:3003"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ARGS=--log-both
      - baseUrl=http://x.x.x.x 
      - port=3003
      - logLevel=info
      - TZ=America/Los_Angeles
```
